// account action
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGN_UP = 'SIGN_UP'
export const RESEND_LINK = 'RESEND_LINK'
export const CHECK_COOKIE = 'CHECK_COOKIE'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const GET_USER_STUFF = 'GET_USER_STUFF'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE'
export const DELETE_USER_STUFF = 'DELETE_USER_STUFF'
export const EMAIL_CONFIRMATION = 'EMAIL_CONFIRMATION'
export const STAY_USER_CONNECTED = 'STAY_USER_CONNECTED'
export const LINK_PASSWORD_RESET = 'LINK_PASSWORD_RESET'

// anime action
export const GET_ANIME = 'GET_ANIME'
export const INSERT_ANIME = 'INSERT_ANIME'
export const GET_REVIEWS_ANIME = 'GET_REVIEWS_ANIME'
export const GET_ANIME_FILTERED = 'GET_ANIME_FILTERED'
export const GET_ANIME_SEASON_NOW = 'GET_ANIME_SEASON_NOW'

// character action
export const GET_CHARACTER = 'GET_CHARACTER'

// home action
export const GET_TOP_MANGA = 'GET_TOP_MANGA'
export const GET_ANIME_UPCOMING = 'GET_ANIME_UPCOMING'
export const GET_TOP_CHARACTERS = 'GET_TOP_CHARACTERS'

// manga actions
export const GET_MANGA = 'GET_MANGA'
export const INSERT_MANGA = 'INSERT_MANGA'
export const GET_PICK_MANGA = 'GET_PICK_MANGA'
export const GET_MANGA_FILTERED = 'GET_MANGA_FILTERED'
export const GET_MOST_FAVORITES_MANGA = 'GET_MOST_FAVORITES_MANGA'
export const GET_MANGA_RECOMMENDATIONS = 'GET_MANGA_RECOMMENDATIONS'
